- .github/workflows/tests.yml
- examples/api.ts
- examples/simple-worker.e2e.ts
- package.json
- src/clients/dispatcher/action-listener.ts
- src/clients/rest/generated/Api.ts
- src/clients/rest/generated/data-contracts.ts
- src/clients/worker/worker.test.ts
- src/clients/worker/worker.ts
>  feat(test): add e2e tests

- examples/simple-worker.e2e.ts
Required due to some internal engine changes
> test(e2e): adapt timeout and log timing

- src/clients/hatchet-client/client-config.ts
> fix: tls can be none

- .github/workflows/auto-merge.yml
> ci(auto-merge): add auto merge for dependabot

- generate-protoc.sh
- package.json
- src/clients/admin/admin-client.test.ts
- src/clients/admin/admin-client.ts
- src/protoc/events/events.ts
- src/protoc/workflows/workflows.ts
Updates protoc for the latest version of Hatchet, fix incompats
> fix: update protoc

- package.json
- src/clients/worker/worker.ts
> fix: register workflow race

- .gitmodules
- package.json
- src/clients/dispatcher/action-listener.ts
- src/protoc/dispatcher/dispatcher.ts
Corresponding Typescript SDK changes for https://github.com/hatchet-dev/hatchet/pull/308.
> feat: new listener strategy

- examples/rate-limit/events.ts
- examples/rate-limit/worker.ts
- package.json
- src/clients/admin/admin-client.ts
- src/clients/worker/worker.ts
- src/protoc/workflows/workflows.ts
- src/step.ts
Adds global rate limit support to the typescript SDK
- adds `admin.put_rate_limit`
- adds `rateLimit` prop to step config
> feat: global rate limit

- examples/api.ts
- src/clients/admin/admin-client.ts
- src/clients/listener/listener-client.ts
- src/clients/rest/generated/Api.ts
- src/clients/rest/generated/data-contracts.ts
Adds query for `workflowGetMetrics` to the admin API.
> feat: add metrics query to typescript api

- package.json
- src/step.ts
Add workflowName method to context object to get the name from with in a step run.
> feat: expose workflow name context

- package.json
- src/clients/worker/worker.ts
We were swallowing stack traces for runtime erros
> fix: error stack trace

- package.json
- src/clients/dispatcher/action-listener.ts
- src/clients/dispatcher/heartbeat/heartbeat-controller.ts
- src/clients/dispatcher/heartbeat/heartbeat-worker.ts
- src/clients/hatchet-client/hatchet-client.ts
- src/util/logger/logger.ts
- src/util/thread-helper.ts
Run heartbeat on worker thread to prevent io blocking
> fix: heartbeat reliability

- examples/simple-worker.ts
- package.json
- src/step.ts
> fix: spawn workflow input type

- .github/workflows/auto-merge.yml
Auto approves relevant dependabot PRs due to the new required reviewers.
> chore(auto-merge): approve PR on auto merge

- package.json
- src/clients/rest/generated/Api.ts
- src/clients/rest/generated/data-contracts.ts
> chore: update rest api

- examples/api.ts
- package.json
- src/clients/admin/admin-client.ts
Makes API example more clear and adds some `list_workflow_runs` query options.
> chore: update api example and bump rest api version

- package.json
- src/util/workflow-run-ref.ts
Adds custom `DedupeViolationError` to typescript sdk.
> feat: deduplicated enqueue error

- src/clients/worker/worker.ts
- src/protoc/dispatcher/dispatcher.ts
- src/protoc/events/events.ts
- src/step.ts
Adds additional fields for child workflows to context.
> feat: additional fields in context

- src/clients/worker/handler.ts
For a webhook route /api/webhook, use as follows in `pages/api/webhook.tsx`:
```ts
import { hatchet, workflow, workflow2 } from '@/lib/workflow'
const secret = process.env.HATCHET_WEBHOOK_SECRET || 'secret'
const webhooks = hatchet.webhooks([workflow, workflow2])
export default webhooks.nextJSHandler({ secret })
```
> feat(handler): add nextjs pages router handler

- package.json
- src/clients/listener/listener-client.ts
Adds additional data to streaming endpoints to make it significantly easier to work with child workflows.
> feat: add resourceId and workflowRunId to step run event

- package.json
- src/clients/event/event-client.test.ts
- src/clients/event/event-client.ts
- src/util/retrier.ts
> fix: use `retrier` in event push

- package.json
- src/examples/on-failure.ts
- src/step.ts
Simple getter method for accessing step run errors
> Feat: Add getter for step run errors to context
